version: '3'
services:
  app:
    build:
      context: .
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: mysql:5.7.30
    environment:
      MYSQL_USER: root
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      TZ: Asia/Tokyo
    ports:
      - 3306:3306
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
