version: '3'
services:
  app:
    build:
      context: .
    volumes:
      - .:/app
    depends_on:
      - db
    networks:
      app_net:
        ipv4_address: '172.20.0.1'

  db:
    image: mysql:5.7.30
    environment:
      MYSQL_USER: root
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      TZ: Asia/Tokyo
    ports:
      - 3306:3306
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      app_net:
        ipv4_address: '172.20.0.2'

volumes:
  mysql_data:

networks:
  app_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/24
